[package]
name = "tui-react"
version = "0.19.0"
authors = ["Sebastian Thiel <sthiel@thoughtworks.com>"]
edition = "2018"
repository = "https://github.com/Byron/tui-crates"
description = "TUI widgets using a react-like paradigm, allowing mutable component state and render properties."
readme = "README.md"
license = "MIT"

[dependencies]
ratatui = { version = "0.20.1", default-features = false }
log = "0.4.6"
unicode-segmentation = "1.6.0"
unicode-width = "0.1.7"
